// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC83rHqolnI_t-E6lGBbJ-mwrM5FhvqO30',
    appId: '1:660659064564:android:b7093c8336155cdc3fd8a1',
    messagingSenderId: '660659064564',
    projectId: 'busybeeapp-c24fb',
    storageBucket: 'busybeeapp-c24fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMO_sx7aR5OyHINEtvE-0ECUXJf8JyUXI',
    appId: '1:660659064564:ios:2df655189ab237843fd8a1',
    messagingSenderId: '660659064564',
    projectId: 'busybeeapp-c24fb',
    storageBucket: 'busybeeapp-c24fb.appspot.com',
    androidClientId: '660659064564-l3gqe0e047gkuk93m0gu05ajphni2l2n.apps.googleusercontent.com',
    iosClientId: '660659064564-68bdda3nkmbqlo45q6u0k69gammbpqsn.apps.googleusercontent.com',
    iosBundleId: 'uk.co.busybeelearning.busybeelearning',
  );
}
